18F/guides

.github/workflows/pull-request.yml
.htmlvalidate.json
404.html
_includes/header.html
_includes/layouts/base.html
_includes/menu.html
_includes/meta.html
_includes/usa_identifier.html
admin/index.html
blog/index.html
package-lock.json
package.json

This PR adds automatic HTML validation to to the CI/CD workflow, and fixes some of the initial issues flagged by the test. 
Part of [TLC #295](https://github.com/18F/TLC-crew/issues/295)

Add HTML validation workflow

---

content/ux-guide/research/ethics.md
content/ux-guide/research/share-power.md

Added new content for Ethics and created new page and content for Power Dynamics

Ethics & Power Dynamics

---

docs/adr/001-clarify-dependabot-process.md

Closes https://github.com/18F/TLC-crew/issues/473

Add ADR folder; Add ADR to clarify Dependabot process

---

docs/adr/001-clarify-dependabot-process.md

- Adds a consideration factor on malware and malicious behavior.
- Adopts the proposed solution.
- Removes tracking time saved (unclear how we would track this).
- Adds anticipated consequences.
- Updates the decision to be accepted.
While this changeset is a documentation update, flagging that there are security considerations as a result of this decision that are discussed in the changeset. Namely, this decision increases the risk that we automatically deploy malicious software, but also increases the rate and consistency we apply security updates to fix bugs including removing malicious software and focuses pull request reviewing on larger changesets (minor and major updates).

Accept ADR on Dependabot.

---

.github/ISSUE_TEMPLATE/basic.md

Tweaks to get the first issue template to work

Update and rename basic.yml to basic.md

---

_includes/layouts/base.html
_includes/meta_redirect.html

- Add a noindex meta tag to meta_redirect.html
-
-
None(?)

Add noindex meta tag

---

content/eng-hiring/index.md

- Address TODO in eng hiring guide, progress toward #157

Address TODO in eng hiring guide

---

content/accessibility/index.md

Replace "TODO" with a link to this github repo

Update a11y guide TODO

---

content/brand/introduction.md

Replace "TODO" with a link to this github repo

Update Brand guide todo

---

content/content-guide/our-style/technical-and-interface-writing.md

Replace "TODOs" with links to this github repo

Update content guide to-dos

---

content/ux-guide/resources/interview-debrief-guide.md

Fixed a broken link and restored two Method links in the Interview Debrief Guide

Update UX guide to-dos part 2

---

content/ux-guide/index.md

Fixed contributing links and restored a Methods link

Update UX guide to-dos part 3

---

content/ux-guide/resources.md

Update contributing link and restore Methods like

Update UX guide to-dos part 4

---

content/ux-guide/research/make-research-actionable.md

UX Guide: Update make-research-actionable.md

---

content/ux-guide/design/build-a-prototype.md

UX Guide: update build-a-prototype.md

---

content/ux-guide/our-approach/values-and-principles.md

UX Guide: Update values-and-principles.md

---

content/ux-guide/research/plan.md

UX Guide: Update plan.md

---

content/ux-guide/resources/interview-checklist.md

UX Guide: Update interview-checklist.md

---

content/ux-guide/our-approach/defining-design.md

UX Guide: Update defining-design.md

---

content/ux-guide/research/do.md

UX Guide: Update do.md

---

.github/workflows/pull-request.yml

Remove dependabot auto-merge step from pr workflow

---

_data/redirect_bases.yaml
_data/titles_roots.yaml
_includes/guidelist.html
content/methods/index.md

Closes #225 
- Adds "hello world" page for methods
- Adds link to methods homepage on dev homepage
- Implements meta tag redirects for methods
Tagging @jduss4 for engineering review
None

Add one test page for methods guide

---

docs/adr/002-improve-maintenance-of-assets.md

- Adds ADR to decide on longterm style maintenance for the repo. 
None (documentation only, not a code change)

Add ADR for asset maintenance

---

docs/replatforming.md

- Adds maintainer documentation for permanent client-side redirects
None—docs change only

Add documentation for permanent client-side redirects

---

.eleventy.js
_data/navigation.yaml
_includes/layouts/method-category.html
_includes/methods/markdown/contextual-inquiry.md
_includes/methods/method.html
_includes/methods/print-header.html
content/methods/discover/cognitive-walkthrough.md
content/methods/discover/contextual-inquiry.md
content/methods/discover/index.md
content/methods/fundamentals/privacy.md
content/methods/fundamentals/recruiting.md

- adds category page—example: `/methods/discover/`
None

build multi card page

---

_data/navigation.yaml
_includes/methods/markdown/design-pattern-library.md
_includes/methods/markdown/prototyping.md
_includes/methods/markdown/wireframing.md
content/methods/decide/user-scenarios.md
content/methods/make/design-pattern-library.md
content/methods/make/prototyping.md
content/methods/make/wireframing.md

- adds temporary placeholder for user-scenarios
- need to figure out how to generate links in "why" frontmatter, see issue https://github.com/18F/guides/issues/298
Part of #234

adds make cards

---

docs/adr/README.md

- Add documentation for an ADR process
Relates to [TLC-crew #593](https://github.com/18F/TLC-crew/issues/593)
None - docs change only

Add proposal for managing ADR's

---

_data/navigation.yaml
_includes/methods/markdown/compensation.md
_includes/methods/markdown/privacy.md
_includes/methods/markdown/recruiting.md
content/methods/fundamentals/compensation.md
content/methods/fundamentals/privacy.md
content/methods/fundamentals/recruiting.md

- Add Fundamentals cards: `/methods/fundamentals/`
Part of #234
None

Add fundamentals method cards

---

_includes/methods/print-header.html

- Fixes "see all [category] cards" from single card page
None

fix: methods: see all [category] cards button

---

.github/ISSUE_TEMPLATE/design-review.yml

Add design review issue template

---

_includes/meta.html

Closes #380
- Adds recommended uswds js file to prevent flashes of unstyled content
None / added file is straight from USWDS

Add uswds-init js

---

_data/titles_roots.yaml

Closes #366 
None / content change only

Fix website title

---

_includes/methods/print-header.html

Closes #360 
None / content change only

Add external link icon to print buttons

---

content/methods/decide/content-audit.md
content/methods/discover/kj-method.md
content/methods/make/wireframing.md

- Fix a few more curly apostrophes from https://github.com/18F/guides/pull/424
-
-
None / content change only

Fix: more curly apostrophes

---

_includes/heading-link.html
_includes/methods/method.html
assets/methods/styles/_method.scss

- Adds heading link partial for content that isn't generated through markdown
Closes #274
None / content change only

Manually add heading links to headers in partials

---

_includes/meta.html

Add comment on why prism cdn exists

---

_includes/layouts/base.html
_includes/site-alert.html

Closes #266
Keeping the partial around in case it's useful in the future
None / removing FE code

Remove site alert banner

---

docs/adr/002-improve-maintenance-of-assets.md

Adds updated information to ADR (see PR changes for details). This felt like the best place to put this context, but can make another ADR to supersede this one if needed. 
Closes #251 as unfinished
None / docs change only

Add updated information to css bundling ADR

---

_includes/footer.html

- Adds a link to the 18F site linking policy in the footer.
closes #347

add link to 18F site linking policy

---

README.md

As a part of closing out the consolidation of Guides & Methods, this commit pulls content from our research into the impact of the guides into the README.
- Updates the README.
None, text update to a text file displayed on GitHub only.

Add preamble to README

---

_data/site.yaml
_includes/scripts.html

~~⚠️ Hold on merging this until we can get someone to monitor analytics for a period of time~~ Edit by James: We have the go ahead.
- Resolves https://github.com/18F/TLC-crew/issues/586 for guide urls
None / adding GSA-provided script

Update google analytics script

---

_data/titles_roots.yaml

completed #465
#
>[!TIP]
> we would also need to update this 
https://github.com/18F/guides/blob/b20fb3b96d6758f69dbfa33040fff7b4d8a47266/content/methods/about.md?plain=1#L12
- [affected page](https://methods.18f.gov/about/)
##
https://github.com/18F/guides/blob/b20fb3b96d6758f69dbfa33040fff7b4d8a47266/content/product/about-this-guide/resources.md?plain=1#L40
- [affected page](https://guides.18f.gov/product/resources/)

Update UX Guide title  

---

content/content-guide/our-style/inclusive-language.md

Link to Syracuse U's Disability Cultural Center Language Guide was broken
- Fix broken link
-
-

Fix broken link on inclusive-language.md

---

_data/navigation.yaml

- Updated to Deliver incremental value for TLC issue #254
-
-

Update product nav title

---

content/product/deliver/index.md

- Updated page title and side nav menu to Deliver incremental value for TLC issue #254
-
-

Update page title

---

content/ux-guide/our-approach/defining-design.md
content/ux-guide/research/make-research-actionable.md

- Fixed typo
- Changed a nav item to sentence case
- None, only content change

Allisonpress UX guide typo fixes

---

content/methods/decide/service-blueprint.md

- Updated punctuation in bullets
- Changed sentence structure for blueprint example
None

Updated punctuation in several places and minor sentence structure update

---

content/ux-guide/research/plan.md

- Fix typo
- Reduce judgment of example of substance addiction
- Add missing periods to safety section
n/a

Copyedits to UX research plan page

---

.github/CODEOWNERS

- Configures @MelissaBraxton as an approver for pull requests that touch content on the Methods guide — looks like this never happened, whoops!
- Removes an outdated comment.
None

Add Melissa as Methods reviewer

---

content/engineering/security/secrets.md

- adds secrets guidance to the engineering guide
closes https://github.com/18F/guides/issues/322
Links to external websites

adds secrets guidance to eng guide, coauthor Ryan Ahearn

---

assets/_common/js/app.js

Fixes #282 
- Adds some JavaScript that uses the scroll event to highlight the currently active section (`<h3>`). 
- This code was borrowed from the [USDS sprint website](https://github.com/usds/discovery-sprint-guide/blob/main/assets/js/app.js#L10)
None

Add code to highlight current heading in the sidenav

---

content/ux-guide/resources/research-plan.md

fixed link to research plan content (had been to #methods, pointed to the right one) 
Ticket: https://github.com/18F/TLC-crew/issues/796

Update research-plan.md - link fix

---

content/methods/discover/system-map.md

Adding a new method card for systems mapping to the 18F methods page.
- Adding a new card about systems mapping to the "discover" section of the 18F methods page
None

Create a new method card for systems mapping

---

content/methods/discover/heuristic-evaluation.md

- added link to accessibility checklist under additional resources
None

added link to accessibility checklist under additional resources

---

content/methods/discover/stakeholder-and-user-interviews.md

- Added link to the interview guide on the stakeholder interview method card
None

Added link to the interview guide on the stakeholder interview method card

---

content/ux-guide/research/make-research-actionable.md

User story & blueprint links added
-
-

User story & blueprint links added

---

_data/navigation.yaml
content/methods/validate/metrics.md

added new methods card for metrics and updated navigation

---

content/engineering/about/about.md

**Where this came from:**
This came out of a discussion in engineering leadership on how to incorporate some writing on open source into the guides. This is the first piece of that.
- Adding human centered, open source, and agile mention as a overview of our practices
- Adding a disclaimer to make clear that our recommendations are not enforcement.  
- Removing TTS blurb, since this is part of 18F Guides
n/a

Update intro to the engineering guide

---

content/engineering/security/secrets.md

Fix typo in secrets.md

---

content/engineering/about/resources.md
content/methods/decide/user-stories.md
content/product/about-this-guide/resources.md
content/product/partners/vendor.md

- Update links to DRG in several other 18F guides to point to v2
- https://github.com/18F/TLC-crew/issues/916
None

Drg v2 update guides links

---

content/derisking-government-tech/home/introduction.md

- Added spaces before and after en-dashes to introduction.md to align with 18F style.
-
-

Added spaces before and after en-dashes to introduction.md

---

.github/ISSUE_TEMPLATE/touchpoints.yml

- Introduces a new issue type to document incoming Touchpoints feedback.
None, new issue type in GitHub.

Add Touchpoints issue type.

---

_includes/footer.html

- Minor edits to the footer include for the guides
[Preview URL](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/mr/guides-footer-edits/)

Minor edits in the guides footer

---

content/derisking-government-tech/home/vendor-management.md

- Edited paragraph on recruiting users mentioned in https://github.com/18F/guides/issues/758. 
[Preview URL](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/mr/derisking-guide-edit-recruitment/derisking-government-tech/vendor-management/)

Simplify paragraph on recruiting users
