18F/guides

.github/dependabot.yml
.github/pull_request_template.md
.github/workflows/codeql-analysis.yml
.github/workflows/pull-request.yml
.github/workflows/stale.yml

Closes https://github.com/18F/TLC-crew/issues/276

Add Handbook CI/CD files, disabling some steps for now

---

_includes/meta.html
content/derisking/state-field-guide/3-budgeting-tech.md
docs/replatforming.md

To address [TLC issue 376](https://github.com/18F/TLC-crew/issues/376)
- Add `seo_title` as available front matter option, if the page's `title` is too long or does not give enough context for a sub-60-char `<title>` tag. [See example.](https://federalist-864a0936-e148-4df8-8602-6b0992887566.sites.pages.cloud.gov/preview/18f/approaches/tlc376-page-titles/derisking/state-field-guide/budgeting-tech/)
- Convert Jekyll page descriptions to Eleventy-readable page descriptions. [See example.](https://federalist-864a0936-e148-4df8-8602-6b0992887566.sites.pages.cloud.gov/preview/18f/approaches/tlc376-page-titles/ux-guide/our-approach/values-and-principles/) (Although also note that only pages in the UX Guide have `description` set in front matter.)

Tlc376 page titles

---

.github/CODEOWNERS
README.md

A challenge which we need to solve when consolidating our Guides & Methods is clearly communicating who is responsible for reviewing and approving pull requests, so that the content remains useful and updated. This PR takes a step in that direction. I expect we will need to revisit this plan shortly. 
This is part of the `next` phase of the [Roadmap update in July](https://docs.google.com/presentation/d/1BRkxeic_39_oK-zQYmbfXpCrJuR_MZaZnFmnQS7WSoE/edit#slide=id.g5ecdbbee9e_0_0) — and following up on recommendations made in [#374](https://github.com/18F/TLC-crew/issues/374).
I reached out to those below, to set these expectations: 
> **What I’m asking of you**
>As a part of the broader effort, and in efforts to maintain and update content, the TLC crew will be proposing changes to the …

Clarify who reviews content changes.

---

_includes/layouts/base.html
_includes/site-alert.html

This PR adds a site-wide alert banner that informs visitors about changing URLs for the 18F guides. 
Closes [TLC/451](https://github.com/18F/TLC-crew/issues/451)
👓 [Preview](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/ik/url-banner/)

Add site alert about url change

---

content/agile/agile-is-something-you-are-not-something-you-do.md
content/agile/agile-lexicon.md

This PR updates the permalink for a couple of pages in the agile guide that didn't have the `agile` guide name in the base of the permalink. This brings it in with the pattern we have established for the all of guides. 
👓 [Preview](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/ik/fix-agile-urls/agile/agile-is-something-you-are/)

Add missing guide name to permalinks for agile pages

---

README.md
_data/site.yaml
_data/titles_roots.yaml

This PR updates the default guide name to be "Guides" instead of 18F Approaches. This is noticeable on the home page and on the 404 page. Updated references in the config and README files as well. Closes #97 
👓 [Preview](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/ik/change-default-names/)

Change references to Approaches to Guides

---

config/buildAssets.js

A tiny proposal to change the `console.log` in the esbuild config to a write to `stdout`/`stderr` to avoid triggering the eslint warning – since that will happen on every PR and run of the linter.

Proposal: Silence no-console warn from buildAssets.js

---

.github/workflows/dependabot-auto-merge.yml

Closes issue #109
- Adds github workflow yml file to automerge any pull requests from dependabot for patch updates, using [this example](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request). I removed the check for certain dependency names because we want this to happen for all dependencies. 
- if implemented incorrectly, could auto-merge other types of PR's. Can mitigate this risk by monitoring PR merges for the next few days after merging this.

Add github workflow to automerge dependabot patches

---

.eleventy.js
sitemap.xml.njk

- Adding `asAbsoluteUrl` filter for prepending the site hostname to a given url
- Ensuring that the sitemap renders fully-qualified URLs when in production, as defined by our env.js file
Search.gov requires fully-qualified URLs in order to properly index the site.
No known concerns

Fully-qualified URLs in production sitemap

---

_data/site.yaml
_includes/menu.html

- Reactivate the search bar, which will only appear in the currently replatformed guides (only agile as of this writing)
- Update the site's search config in the site.yaml file
No known concerns
- Start the environment locally or test in the Cloud Pages build for this branch
- Enter a search term like "agile" or "testing" into the search bar at top right of the [agile guide](http://localhost:8080/agile/)
- Ensure the following:
- There are results from `guides.18f.gov/agile`
- There are NOT results from other `guides.18f.gov/<guide-name>` guides
- It is OK if there are also results from `methods.18f.gov` for now 
#114

Re-activating search bar and updating config

---

.github/workflows/dependabot-auto-merge.yml

Because we require 1 approving review in order for any PR to be merged, we need to "approve" the dependabot patch PR's before auto-merging them
If set up incorrectly, this could allow other unintended types of PR's to auto-merge. 
This PR does **not** change the conditional that checks for the types of PR's we want to auto-merge:
```
if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
```
Since we've confirmed that this conditional is working as expected, the above risk is mitigated.

Add approve pr step to dependabot auto-merge workflow

---

.github/workflows/dependabot-auto-merge.yml

- Adds list of other actions that need to pass before checking for Dependabot patches to auto-merge.
This should increase assurance that Dependabot patch PR's are auto-merged only after all other checks pass.

Ensure other checks pass before running dependabot auto-merge action

---

content/engineering/our-approach/architecture-reviews.md
content/engineering/tools/accessibility-scanning.md

+ Update link to `.pa11yci` example file to point to the unified guides `.pa11yci` instead of the to-be-deprecated Accessibility Guide `.pa11yci`.
+ Remove Jekyll example of setting up pa11y since (1) it points to Accessibility Guide as an example, which we are deprecating, and (2) 18F moved away from Jekyll for G&M on the assumption that it was end-of-life software.
+ #157

Address TODOs in Engineering Guide

---

content/product/about-this-guide/index.md

Update links and remove TODOs per [this spreadsheet](https://docs.google.com/spreadsheets/d/10Sxuh78iZqJ8feBzehGpKKYBrTDOgXxjmjggq8FG-Pg/)

Update two hyperlinks to point into the guides repo

---

content/product/about-this-guide/resources.md

- Per #157 
- Removed a `TODO/` from a link URL
- Is removal the correct way to address this TODO? Please check my understanding

Remove TODO from hyperlink

---

content/ux-guide/research/clarify-the-basics.md

- Per ticket #157 
- Remove `TODO\` from a number of hyperlinks
- Per "Restore URL" instructions in [this spreadsheet](https://docs.google.com/spreadsheets/d/10Sxuh78iZqJ8feBzehGpKKYBrTDOgXxjmjggq8FG-Pg/)
- Please check my understanding that this is the correct restoration!
None: restoring existing functionality

Remove TODOs from many links to methods.18f.gov

---

_data/navigation.yaml
content/accessibility/gov-resources.md

- Fixes 404 for `/accessibility/gov-resources` in production by adding a trailing slash to the markdown permalink
Closes #203 
None

Fix: add trailing slash to permalink

---

.github/CODEOWNERS

- Activates brand guide codeowner
Tagging @igorkorenfeld as the codeowner of the brand guide. 
None

Activate brand guide codeowner

---

_data/redirect_bases.yaml

:warning: will be ready for merge Monday, Dec 4
Remove client-side redirects for content, de-risking, ux guides
**Why?**
Now that these guides are fully prepared for release, this performs step 2 of the migration
**Results**
This will "soft" launch the guides by making the new guides available on the web and indexable by web crawlers.
**Considerations**
Content for these guides will now be available in two places on the web: on the old guide domain and on the new guide domain. This isn't great for SEO, so we want to perform steps 3, 4, and 5 shortly after accepting this change.
- content is now available on the web
- content is now indexable by web crawlers

Remove client-side redirects for content, de-risking, ux guides

---

_data/redirect_bases.yaml

- Removes client-side redirect and noindex meta tags for accessibility, eng-hiring, and product guides
- This makes new guides urls available online and reachable by search engines (including search.gov)
This is step #2 ("soft launch") in the [migration guide](https://docs.google.com/document/d/19b1Y2pSyw1EjXzc2XmL-qXqQCfqiVQLkypOO8zJKUKw/edit#heading=h.quhbb0wqtaay)
None

Remove client-side redirect and noindex meta tag for guides batch 2

---

content/content-guide/our-approach/structure-the-content.md
content/content-guide/our-style/abbreviations-and-acronyms.md
content/redirect.html

Implements version of redirect behavior from [TTS handbook](https://github.com/18F/handbook/blob/main/pages/redirect.html)
There were already `redirect_from` properties in the frontmatter of many pages, which I have not altered. I only changed two files for testing:
1. `structure-the-content` because it had duplicate redirects that were causing 11ty to error
2. `abbreviations-and-acronyms` to test a couple redirects for the content-guide
I have concerns about the absolute vs relative URL paths, so we are going to test on production to see if this is working.

incomplete implementation of possible client-side redirect behavior

---

_data/redirect_bases.yaml

Now that client-side redirects are in place, we can soft-launch this guide
- removes temporary client-side redirects for engineering guide and noindex meta tag
This is Step #2 in [migration guide](https://docs.google.com/document/d/19b1Y2pSyw1EjXzc2XmL-qXqQCfqiVQLkypOO8zJKUKw/edit#heading=h.quhbb0wqtaay)
None

Soft-launch engineering guide

---

content/content-guide/about-this-guide/index.md
content/content-guide/our-approach/address-the-user.md
content/content-guide/our-approach/avoid-duplication.md
content/content-guide/our-approach/be-concise.md
content/content-guide/our-approach/gather-feedback.md
content/content-guide/our-approach/index.md
content/content-guide/our-approach/keep-refining.md
content/content-guide/our-approach/make-content-web-friendly.md
content/content-guide/our-approach/plain-language.md
content/content-guide/our-approach/structure-the-content.md
content/content-guide/our-style/active-voice.md
content/content-guide/our-style/capitalization.md
content/content-guide/our-style/inclusive-language.md
content/content-guide/our-style/index.md
content/content-guide/our-style/names.md
content/content-guide/our-style/numbers-and-percentages.md
content/content-guide/our-style/punctuation.md
content/content-guide/our-style/specific-words-and-phrases.md
content/content-guide/our-style/style-guides.md
content/content-guide/our-style/technical-and-interface-writing.md
content/content-guide/our-style/trademarks-and-brands.md
content/content-guide/our-style/urls-and-filenames.md
content/content-guide/our-style/voice-and-tone.md
content/derisking/qasp.md

- updates `redirect_from` directives to conform to urls from the old guide sitemap for content guide and 1 derisking guide url. 
None

Fix client-side redirects for content guide

---

content/content-guide/our-approach/index.md

- redirects `/content-guide/content-principles` to `/content-guide/our-approach`
-
-
None

Fix one more content guide redirect

---

.github/CODEOWNERS

- Activate github codeowners for these guides, so that they'll be notified of pull requests for their guide
None as this is not a functional change

Activate codeowners for content, derisking, ux guides

---

content/methods/about.md
content/methods/decide/index.md
content/methods/fundamentals/index.md
content/methods/make/index.md
content/methods/validate/index.md

- Adds About page to Methods guide: `/methods/about/`
- Adds placeholder pages to make link tests pass
@juliaklindpaintner @christophermather The current Methods guide has a list of [release notes](https://methods.18f.gov/about/#release-notes) at the bottom of its About page. Considering that we're changing how guides are maintained, do we want to keep the practice of publishing release notes for Methods?
Closes #232 
None

Add about page to methods guide

---

_data/navigation.yaml
_includes/methods/markdown/design-studio.md
_includes/methods/markdown/dot-voting.md
_includes/methods/markdown/five-whys.md
_includes/methods/markdown/heuristic-evaluation.md
_includes/methods/markdown/hopes-and-fears.md
_includes/methods/markdown/kj-method.md
_includes/methods/markdown/lean-coffee.md
_includes/methods/markdown/stakeholder-and-user-interviews.md
_includes/methods/markdown/stakeholder-influence-mapping.md
content/methods/decide/comparative-analysis.md
content/methods/decide/personas.md
content/methods/discover/cognitive-walkthrough.md
content/methods/discover/contextual-inquiry.md
content/methods/discover/design-studio.md
content/methods/discover/dot-voting.md
content/methods/discover/five-whys.md
content/methods/discover/heuristic-evaluation.md
content/methods/discover/hopes-and-fears.md
content/methods/discover/kj-method.md
content/methods/discover/lean-coffee.md
content/methods/discover/stakeholder-and-user-interviews.md
content/methods/discover/stakeholder-influence-mapping.md
content/methods/interview-checklist.md

Changed link style from `<a>` to markdown `[]()` for consistency
Roughs in three pages to prevent broken links:
- comparative analysis
- personas
- interview checklist
A portion of #234

Adds method guide cards from discovery category

---

_data/method_categories.yaml
_includes/layouts/method-card.html
_includes/layouts/method-category.html
_includes/methods/homepage-category.html
_includes/methods/homepage-methods-include.html
assets/methods/styles/_category.scss
assets/methods/styles/_homepage.scss
assets/methods/styles/methods-styles.scss
content/methods/fundamentals/compensation.md
content/methods/index.md
content/methods/make/design-pattern-library.md

- Adds content and styling for methods landing page: `/methods/`
- Cleans up methods categories data—listing of each method for each category wasn't needed, and `category_` on keys was redundant
Same known issues as in https://github.com/18F/guides/pull/273
Closes #233
None

Initial methods landing page

---

content/methods/interview-checklist.md
content/methods/interview-debrief.md
content/methods/validate/usability-testing.md

- Adds `/methods/interview-checklist/` and `/methods/interview-debrief` pages, along with stubbed out pages that are linked from these pages.
None

Add interview checklist and debrief pages

---

assets/_common/styles/custom-styles.scss
assets/derisking/styles/derisking-styles.scss
content/methods/interview-checklist.md

Demonstrates what using the derisking guide styled checklists would look like for methods guide checklists, which are currently unstyled. 
Compare:
- [live derisking checklists](https://guides.18f.gov/derisking/state-field-guide/budgeting-tech/#checklist)
- For demo methods checklists, go to: `/methods/interview-checklist/` on the latest PR build
Closes #294 
None / style change only

Use Derisking guide styled checklists for methods checklists

---

assets/_common/styles/custom-styles.scss
content/ux-guide/resources/interview-checklist.md
content/ux-guide/resources/participant-agreement.md
content/ux-guide/resources/research-alignment-workshop.md

- Closes #341
- Handles single checkboxes with a simpler styling (example on `/ux-guide/participant-agreement/`)
None / style change only

Apply derisking guide checkbox style throughout guides

---

assets/_common/styles/custom-styles.scss
assets/methods/styles/_interview-script.scss
assets/methods/styles/methods-styles.scss
content/ux-guide/resources/usability-test-guide.md

eventually there may not be two separate scripts but until such a time, moved the style into a common location
closes https://github.com/18F/guides/issues/430
- adds class to ux-guide user interview script
- moves css style to common location rather than methods specific
[Methods version](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/jvd-430/methods/interview-script/)
[UX Guide version](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/jvd-430/ux-guide/usability-test-script/)

adds highlighting to usability test script

---

content/derisking/federal-field-guide/1-introduction.md
content/derisking/federal-field-guide/2-basic-principles.md
content/derisking/federal-field-guide/3-planning.md
content/derisking/federal-field-guide/4-deciding-what-to-buy.md
content/derisking/federal-field-guide/5-doing-the-work.md
content/derisking/federal-field-guide/6-appendix.md
content/derisking/index.html
content/derisking/qasp.md
content/derisking/state-field-guide/1-introduction.md
content/derisking/state-field-guide/2-basic-principles.md
content/derisking/state-field-guide/3-budgeting-tech.md
content/derisking/state-field-guide/4-questions-to-ask.md

- Adding meta descriptions for pages in the de-risking guide drafted by @ameliaswong [here ](https://docs.google.com/spreadsheets/d/13MyoRtlR3nFx2iMvu932RBiHrAJ5-kiiKAHmgthh4Q4/edit#gid=406468427)
- Improve SEO and findability
None

add meta descriptions to de-risking guide

---

content/accessibility/headings.md
content/methods/interview-checklist.md
content/ux-guide/resources/interview-checklist.md
docs/development.md

- Replace "the the" and "teh" with "the"

Fix common typos for the word "the"

---

_includes/usa_identifier.html

- Remove `aria-label="Agency description"` from a `<div>` element
- The label is not allowed on `<div>` elements [by html-validate](https://html-validate.org/rules/aria-label-misuse.html)
- Which is causing HTML validation dependabot updates [like this one](https://github.com/18F/guides/pull/494) to fail
- 🤔 Are there a11y concerns?

Remove aria-label on div element

---

_data/titles_roots.yaml

Remove the word "Design" from the title of the User Experience Guide, per the [TLC ticket](https://github.com/18F/guides/issues/465) and previous [merged PR](https://github.com/18F/guides/pull/467/files).

Update UX Guide title

---

_includes/guidelist.html
_includes/hero.html

The `index.html` page in this repository doesn't actually appear online at guides.18f.gov/. But in a Cloud.gov Pages preview, we do see that page. This can be confusing, so this PR adds content on the `index.html` page that tries to explain the situation.
HTML content-only change so no security implications.

Clarify the role of the home page in the guides repo

---

docs/development.md

This PR adds some documentation on how developers should handle the dependency updates from Dependabot. @juliaklindpaintner this is my first try at documenting what I would do.
Just documentation changes, no security considerations

Document how to deal with Dependabot PRs

---

_includes/footer.html

- Fixed the mailto link in the footer so that it correctly sends to 18f@gsa.gov, fixes #527 
None

Add 'f' to the email address for 18F

---

content/engineering/our-approach/architecture-reviews.md
content/methods/fundamentals/privacy.md

- Updated links in Engineering and Methods guides
- Will be further tackled via https://github.com/18F/guides/issues/535
Content change only, no concerns

Fix 404 guide links

---

.github/CODEOWNERS

- As per [this comment](https://github.com/18F/guides/issues/253#issuecomment-2121300141), Lalitha is now the Product guide owner. Updating CODEOWNERS to tag her appropriately in pull requests.
None.

Update Product guide owner

---

content/engineering/tools/books-we-have-read.md
content/engineering/tools/continuous-deployment.md
content/engineering/tools/datastore-selection.md
content/engineering/tools/diagramming.md
content/engineering/tools/sharepoint.md
content/engineering/tools/web-architecture.md

- #327 
- Creates a new page to suggest PlantUML, Mermaid, and Graphviz with links to examples and documentation.
None, this is a content-only change

Create a new page for diagramming tools

---

assets/methods/styles/_method.scss

This is a proposed fix for #420, to close up the leading on `.method-title` elements.
Here's the default/current treatment of the element:
Here's the updated treatment, once the below fix is applied:
No security considerations AFAIK; this is a CSS-only change.

Reduced line-height on .method--title (#420)

---

content/derisking/federal-field-guide/1-introduction.md
content/derisking/state-field-guide/1-introduction.md
content/derisking/state-field-guide/3-budgeting-tech.md

From #559 Decide to remove links to external PDFs that trigger a 403 error
- Removed the links to the offending PDFs but kept the footnotes.
- This removes links that violate the GSA IT General Rules of Behavior

Removed links to the PDFs but kept the footnotes.

---

content/engineering/tools/laptop-setup.md

From: Fix links resulting in a 403 error on guides.18f.gov #537 
- Remove link to Spectacle App website from the [Laptop setup page](https://guides.18f.gov/engineering/tools/laptop-setup/).
- This fixes a security issue. The link being removed points to a site that has been compromised.

Remove link to Spectacle from Laptop Setup page

---

content/ux-guide/resources/research-plan.md

- Updating the content of the research plan template on the UX guide 
- changes the structure of headers
- streamlines content with links into guide
- remove left navigation
- change page title and seo title (note that this may change again depending on other work) 
Addresses https://github.com/18F/TLC-crew/issues/796 
none

update to research plan template 

---

content/methods/discover/system-map.md

Removed the links in the "what" section of the card since the markdown wasn't rendering correctly. Also fixed a spelling error in the title of the card.
-
-
-

Remove links in system-map.md front matter

---

.github/CODEOWNERS

Update the codeowners for UX Guide and Methods to be @quarterback

Update CODEOWNERS for UX Guide and Methods

---

content/brand/templates.md

This PR removes the button link to the GSA slide gallery from the Brand guide's templates page. @claireb-gsa discovered that any presentation created using the 18F template after clicking on this link was placed in the 18F template presentations folder. This creates a lot of files with the duplicate title "18F Slide Theme" which make it difficult to tell which file is actually the theme file and which are copies, and generally leads to a more cluttered folder.  
👓 [Preview](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/ik/remove-slide-gallery-button/brand/templates/)

Remove link to GSA slide gallery

---

_includes/derisking/redirect_url.html
_includes/header.html
content/derisking/federal-field-guide/1-introduction.md
content/derisking/federal-field-guide/2-basic-principles.md
content/derisking/federal-field-guide/3-planning.md
content/derisking/federal-field-guide/4-deciding-what-to-buy.md
content/derisking/federal-field-guide/5-doing-the-work.md
content/derisking/federal-field-guide/6-appendix.md
content/derisking/index.html
content/derisking/qasp.md
content/derisking/state-field-guide/1-introduction.md
content/derisking/state-field-guide/2-basic-principles.md
content/derisking/state-field-guide/3-budgeting-tech.md
content/derisking/state-field-guide/4-questions-to-ask.md

- Adds notification bar and conditional logic to render it on /derisking pages with a 'redirect-url' variable
- adds redirect-urls to pages in the original guide that point to corresponding pages in the new guide
- https://github.com/18F/TLC-crew/issues/917
None

Add alert banner and redirects from v1 of DRG to v2

---

.eleventy.js
robots.txt

Closes #243 
- adds a robots.txt file to the guides repo
- allows all robots, specifies that search.gov can index a page every 2 seconds
Questions:
- are there any agents that we want to address specifically?
- are there any pages that we don't want crawled?
No concerns.

adds robots.txt per search.gov recs

---

_includes/meta.html

Per discussion with @ameliaswong, we'd like X/Twitter cards for Guides pages to display the full page title, with " | 18F <guide title>" appended.
For example: currently an X card for https://guides.18f.gov/methods/decide/service-blueprint/ shows the title as "Service blueprint", rather than "Service blueprint | 18F Methods".
This PR removes the `twitter:title` meta tag from Guides pages. Per X [developer documentation](https://developer.x.com/en/docs/x-for-websites/cards/guides/getting-started#opengraph): "When the Twitter card processor looks for tags on a page, it first checks for the Twitter-specific property, and if not present, falls back to the supported Open Graph property." For Guides pages, `og:title` contains the desired text and matches each page's `title` element.
This work …

Remove `twitter:title` meta tag

---

content/brand/icons.md

- Add a link to the "Icons" page of the Brand Guide that links to the Feather Icon library in Figma, which is replacing our Sketch file. 
- Add a note that the Sketch file is now deprecated.
None that I'm aware of.

Brand Guide: Add a link to the Feather Icon library in Figma

---

content/engineering/languages-runtimes/python.md
content/engineering/security/content-security-policy.md

[Ruff](https://github.com/astral-sh/ruff) is a newer project from only a few years ago that does all the things flake8/isort/black does, but in one package, and is much faster. I think suggesting ruff for new projects would help have less tools to run and set up, and also reduce cycle time by making it run anywhere from slightly to much faster than flake8 depending on the size of the project. This would also pave the way for standardizing on it down the line if adoption is a success.
This PR also adds [poetry](https://python-poetry.org/) as another option for a package manager.
Also while I was in here, I found a few blacklist/whitelist references and changed them to allowlist/denylist.
The docs portion shouldn't have any security concerns. Additionally, ruff runs locally and you can …

Suggest replacing flake8/isort/black with ruff

---

_data/site.yaml
_includes/layouts/base.html
_includes/scripts.html
_includes/touchpoints-button.html
assets/_common/styles/custom-styles.scss
docs/development.md

Integrate Touchpoints user feedback surveys into all 18F Guides pages. See the updated [developer docs](https://github.com/18F/guides/pull/723/files#diff-97db29a7915320e63d41d38a0440360a87055ee8ed03757aa263116dbbb4aabe) for details.
Resolves https://github.com/18F/TLC-crew/issues/885.
The Touchpoints form is integrated via two code sources:
1. Javascript that is fetched from the Touchpoints application and run at page load time.
2. A button element with custom styling within this project's page layout code.
The script URL and the button element ID are both properties of the Touchpoints form configuration and are subject to change, although changes are likely to be infrequent. For maintainability I've defined those values within this project's site configuration file, instead of hardcoding …

Implement Touchpoints feedback survey

---

_includes/menu.html
assets/_common/styles/custom-styles.scss
assets/_common/styles/overrides/extended-header.scss
docs/development.md

Display an icon next to download links in the primary navigation. Currently this is used only in the de-risking guide.
Resolves https://github.com/18F/guides/issues/704.
When the page is at least 64em wide and the primary nav is shown in the page header, conditionally set a 1-pixel top margin on the icon in order to optically center it. This isn't necessary in narrower screens, when the primary nav moves to the Menu drop-down. This is implemented within the existing media rule for the extended header styles.
Manually test the primary nav in [this PR's build](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/guides-704-download-icon/derisking-government-tech/).
- Visit any page in the de-risking guide.
- Confirm that the "Download" link shows …

Add file download icon to de-risking guide primary nav

---

content/methods/validate/card-sorting.md

#711 has a straightforward request to add a link to a card sort template on Figma.
- Add the requested link to the template on the card sort method card
None, just adding one link.

Add link to our Figma card sort template

---

assets/_common/styles/custom-styles.scss

#207 asks for a fix to orphaned permalink icons on headings that are a particular length relative to the column width. @beepdotgov suggested `text-wrap: balance` in that ticket and it appears to do what we want.
(I had some difficulties getting the change to show up in the generated styles-XXXXXXXX.css file, but eventually it did and I think that it will work right in the build after the PR is merged.)
- Add `text-wrap: balance` to H2 elements
None because a purely visual change

#207: Wrap h2 balanced to keep long headings together with their permalinks

---

README.md
docs/analytics.md

Add documentation of how to retrieve analytics data to illustrate the guides' impact and reach.
Minimal. This change adds documentation only. The new docs include links to internal resources (in Google Docs and Google Analytics) but these are gated by Google system authorization controls.

Add docs page for analytics data

---

content/engineering/languages-runtimes/language-selection.md
content/engineering/languages-runtimes/nodejs.md
content/engineering/languages-runtimes/python.md
content/engineering/languages-runtimes/ruby.md

- Update 5 links which point to the archived `development-guides` repo so they point to this repo instead.
- Update 3 links which reference "submitting an issue" so they send the user to the `/issues/new` endpoint on said repo.
No security considerations as a review of the link's content here should be enough to ensure they are not leading users to an unintended location.

Update links which reference archived repo

---

content/methods/validate/content-highlighter-testing.md

- Add new method for content highlighter testing
- Updated standard content re: PRA based on latest OIRA guidance. If this language is accepted, I'll make similar changes on other methods that reference PRA.
- I propose we change "Considerations for use in government to "Government considerations" on all cards that have that section. 
[Preview URL](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/mr/content-highlight-method-card/methods/validate/content-highlighter-testing/)

Add new method card for content highlighter testing

---

content/accessibility/index.md
content/content-guide/our-approach/be-concise.md
content/content-guide/our-style/inclusive-language.md
content/engineering/about/resources.md
content/engineering/tools/accessibility-scanning.md
content/methods/discover/system-map.md
content/ux-guide/our-approach/defining-design.md
content/ux-guide/research/legal.md

- These broken links were noted in a Siteimprove report.
- A few of the commits have a comment where some explanation might be helpful.

Fix broken links in the guides

---

content/agile/modern-software-product-development.md

- Use sentence case for "Modern software product development"
[URL preview](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/agile-guide-minor-edits/agile/modern-software-product-development/)

 Use sentence case for "Modern software product development"

---

content/methods/decide/user-scenarios.md

Copied change from https://github.com/18F/guides/pull/649 to see if checks would move forward (as they didn't with the previous PR). cc: @makaylahipke
Removed broken link to Usability.gov and "Additional resources" subheading.
Changes proposed in this pull request:
Usability.gov is now offline and redirecting to a topic page on digital.gov.
Suggest removing this link and the associated subheading since it no longer leads to relevant content.

Remove outdated link

---

content/brand/images.md

This PR updates the name of 18F peeps to 18F Folks and updates copy on the page. Note that this PR supersedes #722 – It is a duplicate of the work but with a single signed commit (The original PR had missing signed commits and squashing was difficult due to the time gap and interweaving commits). I have done this manually by copy-pasting the text changes. 
Original Authors:
@mitogi 
@michelle-rago

Update 18F peeps to 18F Folks, updates to copy on the brand images page

---

content/engineering/languages-runtimes/language-selection.md

Just what it says on the tin.
None

Remove Jekyll and Hugo as SSG "frequently-used frameworks" and replace with 11ty
